printingNumbers: printingN.c
	gcc printingN.c -o printingN

prime: primes.c
	gcc primes.c -o primes

getPrimes: printingNumbers prime
	./printingN | ./primes | ./primes | ./primes | ./primes | ./primes | ./primes | ./primes | ./primes | ./primes | ./primes | ./primes | ./primes | ./primes | ./primes | ./primes